version: '3.7'

services:
  whmcs: &whmcs
    build: &build
      context: ./docker
      dockerfile: Dockerfile
      args:
        php_version: 7.4
        #whmcs_src: whmcs_v630_full.zip
        #whmcs_src: whmcs_v8.5.1_full.zip
        whmcs_src: whmcs-8.12.1-release.1.zip
        #whmcs_src: whmcs_v790_beta1_full.zip
    networks:
      whmcs_net:
        ipv4_address: 172.16.16.10
    depends_on:
      - mysql
    ports:
      - 80:80
    volumes:
      - ./src/modules/gateways/begateway:/app/modules/gateways/begateway
      - ./src/modules/gateways/callback/begateway.php:/app/modules/gateways/callback/begateway.php
      - ./src/modules/gateways/begateway.php:/app/modules/gateways/begateway.php
    restart: always

  mysql:
    image: mariadb:10.9
    restart: always
    networks:
      whmcs_net:
        ipv4_address: 172.16.16.20
    volumes:
      - /var/lib/mysql
      - ./docker/etc/mysql/mysql.conf.d/sql_mode.cnf:/etc/mysql/mysql.conf.d/sql_mode.cnf
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: whmcs

networks:
  whmcs_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.16.0/24"
